# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Vue & Node JS CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      # - name: Use Node.js ${{ matrix.node-version }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      # - run: npm test

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/yusufprog/apps/etrans-web
            git pull origin

            docker-compose exec npm npm install
            docker-compose exec npm npm run build

            docker network ls | grep -wq apps_default || docker network create apps_default

            docker-compose down
            docker-compose up -d --force-recreate

            #docker-compose down
            #docker-compose up -d
